jwt:
    issuer: https://disney.com
    audience: https://localhost:5001
    secret: fcrvBbXi1Aimu6sIiZMlcvIP9CqjYjVd
db:
    connectionString: "Server=localhost;Database=conlang;User=root;Password=password"
